/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoconsultoriom;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import proyectoconsultoriom.Listas.Nodo;
import static proyectoconsultoriom.ProyectoConsultorioM.admin;

/**
 *
 * @author ulacit
 */
public class Cita extends javax.swing.JFrame {

    public static Paciente paciente;
    private Nodo nodo;
    /**
     * Creates new form Cita
     */
    public Cita() {
        initComponents();
        this.setLocationRelativeTo(null);
        //System.out.println(paciente.getNombre());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtsetcalendar = new com.toedter.calendar.JCalendar();
        calendario2 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        btnagregar = new javax.swing.JButton();
        btnsiguiente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtmotivo = new javax.swing.JTextField();
        combohora = new javax.swing.JComboBox<>();
        combomin = new javax.swing.JComboBox<>();
        txtsethora = new javax.swing.JTextField();
        txtsetmotivo = new javax.swing.JTextField();
        btnregresar1 = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtsetcalendar.setEnabled(false);
        jPanel1.add(txtsetcalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 68, 345, 213));
        jPanel1.add(calendario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 208, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de citas ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        btnagregar.setBackground(new java.awt.Color(204, 204, 255));
        btnagregar.setText("AGREGAR CITA");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        btnsiguiente.setBackground(new java.awt.Color(204, 204, 255));
        btnsiguiente.setText("SIGUIENTE");
        btnsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnsiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        jLabel2.setText("Hora");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        jLabel4.setText("Motivo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));
        jPanel1.add(txtmotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 150, -1));

        combohora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18" }));
        jPanel1.add(combohora, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, -1));

        combomin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "15", "30", "45" }));
        jPanel1.add(combomin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, -1));
        jPanel1.add(txtsethora, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 100, -1));
        jPanel1.add(txtsetmotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 100, -1));

        btnregresar1.setBackground(new java.awt.Color(204, 204, 255));
        btnregresar1.setText("REGRESAR");
        btnregresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnregresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, -1, -1));

        btnreset.setBackground(new java.awt.Color(204, 204, 255));
        btnreset.setText("RESETEAR");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel1.add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clinica Fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 680, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        // TODO add your handling code here:
        /*System.out.println(this.calendario2.getDate());
        this.calendario1.setDate(this.calendario2.getDate());*/
        Date fecha = this.calendario2.getDate();
        String hora = this.combohora.getSelectedItem().toString() + ":" + this.combomin.getSelectedItem().toString();
        String motivo = this.txtmotivo.getText();
        admin.agregarCita(paciente, fecha, hora, motivo);
        admin.mostrarCitas(paciente);
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btnsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguienteActionPerformed
        // TODO add your handling code here:
        nodo = admin.getNodoPaciente(paciente.getId());
       
        if (paciente.getCitas().temp!=null) {
            Date fecha = paciente.getCitas().temp.cita.getFecha();
            String hora = paciente.getCitas().temp.cita.getHora();
            String motivo = paciente.getCitas().temp.cita.getMotivo();
            this.txtsetcalendar.setDate(fecha);
            this.txtsethora.setText(hora);
            this.txtsetmotivo.setText(motivo); 
            paciente.getCitas().temp = paciente.getCitas().temp.sig;
        }else{
            JOptionPane.showMessageDialog(null,"No tiene mas citas programadas");
        }


    }//GEN-LAST:event_btnsiguienteActionPerformed

    private void btnregresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresar1ActionPerformed
        // TODO add your handling code here:
        BuscarPaciente paciente = new BuscarPaciente();
        paciente.actual = this.paciente;
        paciente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnregresar1ActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        paciente.getCitas().resetTemp();
    }//GEN-LAST:event_btnresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnregresar1;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsiguiente;
    private com.toedter.calendar.JDateChooser calendario2;
    private javax.swing.JComboBox<String> combohora;
    private javax.swing.JComboBox<String> combomin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtmotivo;
    private com.toedter.calendar.JCalendar txtsetcalendar;
    private javax.swing.JTextField txtsethora;
    private javax.swing.JTextField txtsetmotivo;
    // End of variables declaration//GEN-END:variables
}
